name: CI/CD

on:
  push:
    branches:
      - main
  # pull_request:
  #   types: [opened, closed]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies 
      run: npm cache clean --force && npm install

    - name: Build
      run: CI=false npm run build --if-present
    
    - name: Dockerhub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker setup
      uses: docker/setup-buildx-action@v2
    
    - name: Pushear imagen
      run: | 
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/infra-lab-3:${GITHUB_REF##*/}-$git_hash .
          echo "Pusheamos imagen a Docker Hub"
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/infra-lab-3:${GITHUB_REF##*/}-$git_hash
          echo "::set-output name=image::${{ secrets.DOCKER_HUB_USERNAME }}/infra-lab-3:${GITHUB_REF##*/}-$git_hash"
    - name: Actualizar versión
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ./charts/helm/values.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./charts/helm/values.yaml
          
    - name: Pushear cambios
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Versión actualizada